/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appu2_recursividad;

import java.util.InputMismatchException;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Appu2_RecursividadGUI extends javax.swing.JFrame {

    /**
     * Creates new form Appu2_RecursividadGUI
     */
     Random azar = new Random();
    public Appu2_RecursividadGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextNum = new javax.swing.JTextField();
        jButFactorial = new javax.swing.JButton();
        jButSumatoria = new javax.swing.JButton();
        jButPotencia = new javax.swing.JButton();
        jButINum = new javax.swing.JButton();
        jButBinario = new javax.swing.JButton();
        jTextPotencia = new javax.swing.JTextField();
        jLabPotencia = new javax.swing.JLabel();
        jLabResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numero: ");

        jButFactorial.setText("Factorial");
        jButFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButFactorialActionPerformed(evt);
            }
        });

        jButSumatoria.setText("Sumatoria");
        jButSumatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSumatoriaActionPerformed(evt);
            }
        });

        jButPotencia.setText("Potencia");
        jButPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButPotenciaActionPerformed(evt);
            }
        });

        jButINum.setText("Invertir Num");
        jButINum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButINumActionPerformed(evt);
            }
        });

        jButBinario.setText("Binario");
        jButBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButBinarioActionPerformed(evt);
            }
        });

        jTextPotencia.setToolTipText("Activar con click boton potencia");
        jTextPotencia.setEnabled(false);
        jTextPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPotenciaActionPerformed(evt);
            }
        });

        jLabPotencia.setText("Potencia:");
        jLabPotencia.setEnabled(false);

        jLabResultado.setBackground(new java.awt.Color(153, 153, 255));
        jLabResultado.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabPotencia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextNum, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButBinario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButFactorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButSumatoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButINum, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jButPotencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButFactorial)
                    .addComponent(jLabel1)
                    .addComponent(jTextNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButSumatoria)
                    .addComponent(jTextPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabPotencia))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButPotencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButINum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButBinario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButPotenciaActionPerformed
        // TODO add your handling code here:
       int num,pot,resu;
        
        if(!jTextPotencia.isEnabled()){
        jTextPotencia.setEnabled(true);
        jLabPotencia.setEnabled(true);
        }
      
        if(jTextPotencia.getText().length()>0){
        try{
        num = Integer.parseInt(jTextNum.getText());
        pot = Integer.parseInt(jTextPotencia.getText());
        }catch(NumberFormatException ex){
        JOptionPane.showMessageDialog(this, "Error de tipo "+ex.getMessage());
                 int ale = azar.nextInt(15)+5;
                 int alepot = azar.nextInt(ale)+1;
                    JOptionPane.showMessageDialog(this, "Se pondra un dato aleatorio = "+ale+"\ny una potencia de "+alepot);
                    num = ale;
                    pot = alepot;
                }
        resu = MatematicasRec.potencia(num, pot);
        jLabResultado.setText("Potencia de "+num+"^"+pot+" = "+resu);
        }
    }//GEN-LAST:event_jButPotenciaActionPerformed

    private void jTextPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPotenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPotenciaActionPerformed

    private void jButFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButFactorialActionPerformed
        // TODO add your handling code here:
                int num,resu;
                try{
                num = Integer.parseInt(jTextNum.getText());
                }catch(NumberFormatException ex){
                    JOptionPane.showMessageDialog(this, "Error de tipo "+ex.getMessage());
                 int ale = azar.nextInt(15)+5;
                    JOptionPane.showMessageDialog(this, "Se pondra un dato aleatorio = "+ale);
                    num = ale;
                }
                resu = MatematicasRec.factorial(num);
                jLabResultado.setText("Factorial de "+num+" = "+resu);
    }//GEN-LAST:event_jButFactorialActionPerformed

    private void jButSumatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSumatoriaActionPerformed
        // TODO add your handling code here:
                int num,resu;
                try{
                num = Integer.parseInt(jTextNum.getText());
                }catch(NumberFormatException ex){
               JOptionPane.showMessageDialog(this, "Error de tipo "+ex.getMessage());
                 int ale = azar.nextInt(15)+5;
                    JOptionPane.showMessageDialog(this, "Se pondra un dato aleatorio = "+ale);
                    num = ale;
                }
                resu = MatematicasRec.sumatoria(num);
                jLabResultado.setText("Sumatoria de "+num+" = "+resu);
    }//GEN-LAST:event_jButSumatoriaActionPerformed

    private void jButINumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButINumActionPerformed
        // TODO add your handling code here:
                int num;
                try{
                num = Integer.parseInt(jTextNum.getText());
                }catch(NumberFormatException ex){
                System.out.println("Error de tipo "+ex.getMessage());
                 int ale = azar.nextInt(15)+5;
                    System.out.println("Se pondra un dato aleatorio = "+ale);
                    num = ale;
                }
                MatematicasRec.invertirNumGUI(num,jLabResultado);
    }//GEN-LAST:event_jButINumActionPerformed

    private void jButBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButBinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButBinarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Appu2_RecursividadGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Appu2_RecursividadGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Appu2_RecursividadGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Appu2_RecursividadGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Appu2_RecursividadGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButBinario;
    private javax.swing.JButton jButFactorial;
    private javax.swing.JButton jButINum;
    private javax.swing.JButton jButPotencia;
    private javax.swing.JButton jButSumatoria;
    private javax.swing.JLabel jLabPotencia;
    private javax.swing.JLabel jLabResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextNum;
    private javax.swing.JTextField jTextPotencia;
    // End of variables declaration//GEN-END:variables
}
