/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_2019_11_04_aplicacionempleadosherencia;

import javax.swing.JButton;

/**
 *
 * @author admin
 */
public class JFrameMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMenu
     */
    
    private Empleado [] empresa = new Empleado[100];
    
   private int empleadosRegistrados;
    public JFrameMenu() {
        initComponents();
        
        empleadosRegistrados = 0;
        jLabRegistrados.setText(empleadosRegistrados+"");
    }
    
    public void setEmpleado(Empleado e, int idx){
    if(idx>=0&& idx<empresa.length){
    empresa[idx] = e;
    }
    }
    
    public Empleado getEmpleado(int idx){
     if(idx>=0&& idx<empresa.length)
    return empresa[idx];
    else
    return new Empleado();
    }
    
    public int getTamaño(){
    return empresa.length;
    }
    public int getEmpleadosRegistrados(){
    return empleadosRegistrados;
    }
    public boolean agregarEmpleado(Empleado e){
    if(empleadosRegistrados == empresa.length)
    return false;
    
    empresa[empleadosRegistrados] = e;
    empleadosRegistrados++;
    jLabRegistrados.setText(empleadosRegistrados+"");
    return true;
    
    }
    
    
    public JButton getBotonSalida(){
    return jButSalida;
    }
    
    public JButton [] getBotones(){
    JButton [] bot = new JButton [4];
    bot[0] = jButRegistro;
    bot[1] = jButConsulta;
    bot[2] = jButReporte;
    bot[3] = jButSalida;
    return bot;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButRegistro = new javax.swing.JButton();
        jButReporte = new javax.swing.JButton();
        jButConsulta = new javax.swing.JButton();
        jButSalida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabRegistrados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setName("Menu"); // NOI18N

        jButRegistro.setBackground(new java.awt.Color(153, 255, 153));
        jButRegistro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButRegistro.setText("Registro");
        jButRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegistroActionPerformed(evt);
            }
        });

        jButReporte.setBackground(new java.awt.Color(102, 255, 204));
        jButReporte.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButReporte.setText("Reporte");
        jButReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButReporteActionPerformed(evt);
            }
        });

        jButConsulta.setBackground(new java.awt.Color(153, 255, 255));
        jButConsulta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButConsulta.setText("Consulta");
        jButConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButConsultaActionPerformed(evt);
            }
        });

        jButSalida.setBackground(new java.awt.Color(255, 0, 0));
        jButSalida.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButSalida.setText("Salida");
        jButSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSalidaActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Empleados registrados");

        jLabRegistrados.setBackground(new java.awt.Color(51, 255, 153));
        jLabRegistrados.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabRegistrados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabRegistrados.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButConsulta)
                            .addComponent(jButSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabRegistrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabRegistrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSalidaActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButSalidaActionPerformed

    private void jButRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegistroActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        JFrameRegistro frameReg = new JFrameRegistro(this);//this: para grabar en el mismo menu y no crear un nuevo registro 
        frameReg.setVisible(true);
          
    }//GEN-LAST:event_jButRegistroActionPerformed

    private void jButReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButReporteActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        JFrameReporte frameRep = new JFrameReporte(this);//this: para grabar en el mismo menu y no crear un nuevo registro 
        frameRep.setVisible(true);
       
    }//GEN-LAST:event_jButReporteActionPerformed

    private void jButConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButConsultaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        JFrameConsulta frameCon = new JFrameConsulta(this);//this: para grabar en el mismo menu y no crear un nuevo registro 
        frameCon.setVisible(true);
    }//GEN-LAST:event_jButConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButConsulta;
    private javax.swing.JButton jButRegistro;
    private javax.swing.JButton jButReporte;
    private javax.swing.JButton jButSalida;
    private javax.swing.JLabel jLabRegistrados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
