/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_19130519_proyecto_02;

import Utilerias.JTable.ColorCeldas;
import Utilerias.JTable.JTabla;
import java.awt.Color;
import java.util.Random;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author admin
 */
public class PA_19130519_Frame_01 extends javax.swing.JFrame {

    /**
     * Creates new form PA_19130519_Frame_01
     */

    DefaultTableModel modelo;
      ColorCeldas color;
      Ordenar distancia;
    public PA_19130519_Frame_01() {
        initComponents();
        
        modelo = (DefaultTableModel)jTableDistancias.getModel(); //modelo de la tabla 
       jTableDistancias.setShowGrid(true); // pone la cuadricula en la tabla  
    }
    
    public void borrarColor(){
    //borrar colores en la tabla 
    color = new ColorCeldas(jTableDistancias);
    for(int r=0; r<modelo.getRowCount(); r++)
            for(int c=0; c<modelo.getColumnCount(); c++)
            {
                 if (r==0)
                    color.addCelda(r, c, Color.white);
                  if (r==modelo.getRowCount()-1)
                    color.addCelda(r, c, Color.white);
            }
         
    }
    public void ordenar(){
        //ordenar datos en la tabla 
        for (int r = 0; r < modelo.getRowCount(); r++){
        Distancia dInicial = new Distancia();
        Distancia dFinal = new Distancia();
        
        dInicial.setMilla(Integer.parseInt(modelo.getValueAt(r, 1)+""));
        dInicial.setBraza(Integer.parseInt(modelo.getValueAt(r, 2)+""));
        dInicial.setYarda(Integer.parseInt(modelo.getValueAt(r, 3)+""));
        dInicial.setPie(Integer.parseInt(modelo.getValueAt(r, 4)+""));
        dInicial.setPulgada(Integer.parseInt(modelo.getValueAt(r, 5)+""));
          
        dFinal.setMilla(Integer.parseInt(modelo.getValueAt(r, 6)+""));
        dFinal.setBraza(Integer.parseInt(modelo.getValueAt(r, 7)+""));
        dFinal.setYarda(Integer.parseInt(modelo.getValueAt(r, 8)+""));
        dFinal.setPie(Integer.parseInt(modelo.getValueAt(r, 9)+""));
        dFinal.setPulgada(Integer.parseInt(modelo.getValueAt(r, 10)+""));  
        
        Longitud des = new  Longitud(modelo.getValueAt(r,0)+"",dInicial,dFinal);  
        
        distancia.setRuta(des, r);
        }
    }
    
    public void mostrar(){
        //mostrar datos en la tabla 
         for (int r = 0; r < modelo.getRowCount(); r++) {
            modelo.setValueAt(distancia.getLongitud(r).getDestino(), r, 0);
            modelo.setValueAt(distancia.getLongitud(r).getDinicial().getMilla(),r,1);
            modelo.setValueAt(distancia.getLongitud(r).getDinicial().getBraza(),r,2);
            modelo.setValueAt(distancia.getLongitud(r).getDinicial().getYarda(),r,3);
            modelo.setValueAt(distancia.getLongitud(r).getDinicial().getPie(),r,4);
            modelo.setValueAt(distancia.getLongitud(r).getDinicial().getPulgada(),r,5);
            
            modelo.setValueAt(distancia.getLongitud(r).getDfinal().getMilla(),r,6);
            modelo.setValueAt(distancia.getLongitud(r).getDfinal().getBraza(),r,7);
            modelo.setValueAt(distancia.getLongitud(r).getDfinal().getYarda(),r,8);
            modelo.setValueAt(distancia.getLongitud(r).getDfinal().getPie(),r,9);
            modelo.setValueAt(distancia.getLongitud(r).getDfinal().getPulgada(),r,10);
            
            modelo.setValueAt(distancia.getLongitud(r).distanciaRecorrida(),r,11);         
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDistancias = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSpinCantidad = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButAleatorios = new javax.swing.JButton();
        jLabTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButCalcular = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButAlfabetico = new javax.swing.JButton();
        jButDescendentemente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButColor = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 204));

        jTableDistancias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Destino", "Milla", "Braza", "Yarda", "Pie", "Pulg", "Milla", "Braza", "Yarda", "Pie", "Pulg", "Distancia recorrida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableDistancias);
        if (jTableDistancias.getColumnModel().getColumnCount() > 0) {
            jTableDistancias.getColumnModel().getColumn(0).setPreferredWidth(200);
            jTableDistancias.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTableDistancias.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTableDistancias.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTableDistancias.getColumnModel().getColumn(4).setPreferredWidth(50);
            jTableDistancias.getColumnModel().getColumn(5).setPreferredWidth(50);
            jTableDistancias.getColumnModel().getColumn(6).setPreferredWidth(50);
            jTableDistancias.getColumnModel().getColumn(7).setPreferredWidth(50);
            jTableDistancias.getColumnModel().getColumn(8).setPreferredWidth(50);
            jTableDistancias.getColumnModel().getColumn(9).setPreferredWidth(50);
            jTableDistancias.getColumnModel().getColumn(10).setPreferredWidth(50);
            jTableDistancias.getColumnModel().getColumn(11).setPreferredWidth(150);
        }

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Distancia inicial ");
        jLabel1.setOpaque(true);

        jSpinCantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinCantidadStateChanged(evt);
            }
        });

        jLabel4.setText("Cantidad de destinos");

        jLabel5.setBackground(new java.awt.Color(204, 255, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Distancia final");
        jLabel5.setOpaque(true);

        jButAleatorios.setText("Aleatorios");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jLabTotal.setBackground(new java.awt.Color(153, 255, 204));
        jLabTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabTotal.setOpaque(true);

        jLabel3.setText("Total");

        jButCalcular.setText("Calcular");
        jButCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalcularActionPerformed(evt);
            }
        });

        jLabel2.setText("Orden Alfabético");

        jButAlfabetico.setText("Ordenar");
        jButAlfabetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAlfabeticoActionPerformed(evt);
            }
        });

        jButDescendentemente.setText("Ordenar");
        jButDescendentemente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDescendentementeActionPerformed(evt);
            }
        });

        jLabel6.setText("Orden Descendente");

        jLabel7.setBackground(new java.awt.Color(0, 255, 51));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Mayor distancia");
        jLabel7.setOpaque(true);

        jLabel8.setBackground(new java.awt.Color(255, 255, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Menor distancia");
        jLabel8.setOpaque(true);

        jButColor.setText("Mostrar");
        jButColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButColorActionPerformed(evt);
            }
        });

        jLabel9.setText("Nombre: Roberto Esquivel Troncoso");

        jLabel10.setText("No de control: 19130519");

        jLabel11.setText("No de proyecto: 2");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_19130519_proyecto_02/Proyecto 2.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButAleatorios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(178, 178, 178)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButAlfabetico)
                                    .addComponent(jButDescendentemente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButColor)
                                .addGap(228, 228, 228)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 953, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jButAleatorios)
                    .addComponent(jButCalcular)
                    .addComponent(jLabel9))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel12))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButAlfabetico))
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButDescendentemente)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButColor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinCantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinCantidadStateChanged
        // TODO add your handling code here:   
        //cantidad de filas en el jTable
        modelo.setRowCount((int)jSpinCantidad.getValue());
    }//GEN-LAST:event_jSpinCantidadStateChanged

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        // TODO add your handling code here:
        Random azar = new Random();
        
        // datos aleatorios en el jTable
        for (int r = 0; r < modelo.getRowCount(); r++) {
        modelo.setValueAt(Destino.nextDestinos(), r, 0); //Destino
        modelo.setValueAt(azar.nextInt(20),r,1); //milla inicial
        modelo.setValueAt(azar.nextInt(879),r,2); //Braza inicial
        modelo.setValueAt(azar.nextInt(2),r,3);  //Yarda inicial 
        modelo.setValueAt(azar.nextInt(3),r,4); //Pie inicial 
        modelo.setValueAt(azar.nextInt(12),r,5);  //Pulg inicial

        modelo.setValueAt(20+azar.nextInt(30),r,6); //milla final
        modelo.setValueAt(azar.nextInt(879),r,7); //Braza final
        modelo.setValueAt(azar.nextInt(2),r,8);  //Yarda final 
        modelo.setValueAt(azar.nextInt(3),r,9); //Pie final
        modelo.setValueAt(azar.nextInt(12),r,10);  //Pulg final
        modelo.setValueAt(null,r,11);
        }  
        //se borran los colores 
        borrarColor();
        color.repaint();
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jButCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalcularActionPerformed
        // TODO add your handling code here:
        Distancia dInicial = new Distancia();
        Distancia dFinal = new Distancia();
        Distancia dRecorrida;
        Distancia dTotal = new Distancia();
        
        // Se llena la información 
        for(int r=0; r<modelo.getRowCount(); r++ ){
        dInicial.setMilla(Integer.parseInt(modelo.getValueAt(r, 1)+""));
        dInicial.setBraza(Integer.parseInt(modelo.getValueAt(r, 2)+""));
        dInicial.setYarda(Integer.parseInt(modelo.getValueAt(r, 3)+""));
        dInicial.setPie(Integer.parseInt(modelo.getValueAt(r, 4)+""));
        dInicial.setPulgada(Integer.parseInt(modelo.getValueAt(r, 5)+""));
          
        dFinal.setMilla(Integer.parseInt(modelo.getValueAt(r, 6)+""));
        dFinal.setBraza(Integer.parseInt(modelo.getValueAt(r, 7)+""));
        dFinal.setYarda(Integer.parseInt(modelo.getValueAt(r, 8)+""));
        dFinal.setPie(Integer.parseInt(modelo.getValueAt(r, 9)+""));
        dFinal.setPulgada(Integer.parseInt(modelo.getValueAt(r, 10)+""));        
        
        // Se calcula la distancia recorrida 
        dRecorrida = dFinal.resta(dInicial);
        
        modelo.setValueAt(dRecorrida, r, 11);
        
        
        //se suman las distancias 
        dTotal = dTotal.suma(dRecorrida);
        }
        // Se muestran las distancia total en el jLab 
        jLabTotal.setText(dTotal+"");
                
        
    }//GEN-LAST:event_jButCalcularActionPerformed

    private void jButDescendentementeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDescendentementeActionPerformed
        // TODO add your handling code here:
        distancia = new Ordenar(modelo.getRowCount());  
        color = new ColorCeldas(jTableDistancias);
        
        //ordenar distancias recorridas descendentemente 
        ordenar();
        
        distancia.ordenarDescendente();
        
        mostrar();      
        //borrar colores
        borrarColor();
        color.repaint();
    }//GEN-LAST:event_jButDescendentementeActionPerformed

    private void jButAlfabeticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAlfabeticoActionPerformed
        // TODO add your handling code here:
       
        //Ordenar alfabeticamente //se llena la informacion 
        Ordenar alfabetico = new Ordenar(modelo.getRowCount());  
        for (int r = 0; r < modelo.getRowCount(); r++){
        Distancia dInicial = new Distancia();
        Distancia dFinal = new Distancia();
        
        dInicial.setMilla(Integer.parseInt(modelo.getValueAt(r, 1)+""));
        dInicial.setBraza(Integer.parseInt(modelo.getValueAt(r, 2)+""));
        dInicial.setYarda(Integer.parseInt(modelo.getValueAt(r, 3)+""));
        dInicial.setPie(Integer.parseInt(modelo.getValueAt(r, 4)+""));
        dInicial.setPulgada(Integer.parseInt(modelo.getValueAt(r, 5)+""));
          
        dFinal.setMilla(Integer.parseInt(modelo.getValueAt(r, 6)+""));
        dFinal.setBraza(Integer.parseInt(modelo.getValueAt(r, 7)+""));
        dFinal.setYarda(Integer.parseInt(modelo.getValueAt(r, 8)+""));
        dFinal.setPie(Integer.parseInt(modelo.getValueAt(r, 9)+""));
        dFinal.setPulgada(Integer.parseInt(modelo.getValueAt(r, 10)+""));  
        
        Longitud des = new Longitud(modelo.getValueAt(r,0)+"",dInicial,dFinal);  
        
       alfabetico.setRuta(des, r);
        }
        
         // Se ordena la información
       alfabetico.ordenarAlfabetico();
         // Se muestra en la tabla   
       for (int r = 0; r < modelo.getRowCount(); r++) {
            modelo.setValueAt(alfabetico.getLongitud(r).getDestino(), r, 0);
            modelo.setValueAt(alfabetico.getLongitud(r).getDinicial().getMilla(),r,1);
            modelo.setValueAt(alfabetico.getLongitud(r).getDinicial().getBraza(),r,2);
            modelo.setValueAt(alfabetico.getLongitud(r).getDinicial().getYarda(),r,3);
            modelo.setValueAt(alfabetico.getLongitud(r).getDinicial().getPie(),r,4);
            modelo.setValueAt(alfabetico.getLongitud(r).getDinicial().getPulgada(),r,5);
            
            modelo.setValueAt(alfabetico.getLongitud(r).getDfinal().getMilla(),r,6);
            modelo.setValueAt(alfabetico.getLongitud(r).getDfinal().getBraza(),r,7);
            modelo.setValueAt(alfabetico.getLongitud(r).getDfinal().getYarda(),r,8);
            modelo.setValueAt(alfabetico.getLongitud(r).getDfinal().getPie(),r,9);
            modelo.setValueAt(alfabetico.getLongitud(r).getDfinal().getPulgada(),r,10);
            
            modelo.setValueAt(alfabetico.getLongitud(r).distanciaRecorrida(),r,11);
        }
         //se borran los colores en el jTable
          borrarColor();
            color.repaint();
           
    }//GEN-LAST:event_jButAlfabeticoActionPerformed

    private void jButColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButColorActionPerformed
        // TODO add your handling code here:
        distancia = new Ordenar(modelo.getRowCount());  
        color = new ColorCeldas(jTableDistancias);
        // Se ordena 
        ordenar();
        distancia.ordenar();
        
        // Se muestra en la tabla 
       mostrar();
        
       // Se colorea el mayor y el menor 
          for(int r=0; r<modelo.getRowCount(); r++)
            for(int c=0; c<modelo.getColumnCount(); c++)
            {
                 if (r==0)//primer renglon
                    color.addCelda(r, c, Color.yellow);
                  if (r==modelo.getRowCount()-1)//ultimo renglon
                    color.addCelda(r, c, Color.green);
            }
          color.repaint();
    
    
        
    }//GEN-LAST:event_jButColorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PA_19130519_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PA_19130519_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PA_19130519_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PA_19130519_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PA_19130519_Frame_01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButAlfabetico;
    private javax.swing.JButton jButCalcular;
    private javax.swing.JButton jButColor;
    private javax.swing.JButton jButDescendentemente;
    private javax.swing.JLabel jLabTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinCantidad;
    private javax.swing.JTable jTableDistancias;
    // End of variables declaration//GEN-END:variables
}
