/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appexpregulargui;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javafx.scene.control.RadioButton;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextCadena = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextPatron = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaResultadoBusqueda = new javax.swing.JTextArea();
        jButBuscar = new javax.swing.JButton();
        jButCoincide = new javax.swing.JButton();
        jButRemplazar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(), "Busqueda"));

        jLabel1.setText("Cadena");

        jTextCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCadenaActionPerformed(evt);
            }
        });

        jLabel2.setText("Patron");

        jTextAreaResultadoBusqueda.setColumns(20);
        jTextAreaResultadoBusqueda.setRows(5);
        jScrollPane1.setViewportView(jTextAreaResultadoBusqueda);

        jButBuscar.setText("Buscar");
        jButBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButBuscarActionPerformed(evt);
            }
        });

        jButCoincide.setText("Coincide");
        jButCoincide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCoincideActionPerformed(evt);
            }
        });

        jButRemplazar.setText("Remplazar");
        jButRemplazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRemplazarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextCadena, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                            .addComponent(jTextPatron))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButCoincide)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButRemplazar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextCadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButCoincide)
                    .addComponent(jButRemplazar))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextPatron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButCoincideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCoincideActionPerformed
        // TODO add your handling code here:
       jTextAreaResultadoBusqueda.setText("");
        String cadena = jTextCadena.getText();
        Pattern patron = Pattern.compile(jTextPatron.getText());
        Matcher matcher = matcher = patron.matcher(cadena);
        String todo = "1";
        try{
         todo = JOptionPane.showInputDialog("Coincidir con toda la cadena \n1.Si\n2.No");
        }catch(NumberFormatException ex){
            todo = "2";
        }
        int opc = Integer.parseInt(todo);
        if(opc == 1){
        if(matcher.matches())
            jTextAreaResultadoBusqueda.setText("Coincide");
        else 
            jTextAreaResultadoBusqueda.setText("No coincide");
        }else {
            if(matcher.lookingAt())
            jTextAreaResultadoBusqueda.setText("Coincide");
        else 
            jTextAreaResultadoBusqueda.setText("No coincide");
        }
            
    }//GEN-LAST:event_jButCoincideActionPerformed

    private void jButBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButBuscarActionPerformed
        // TODO add your handling code here:
        jTextAreaResultadoBusqueda.replaceSelection(" ");
        jTextAreaResultadoBusqueda.setText("");
         String REGEX = jTextPatron.getText();
         String INPUT = jTextCadena.getText();

        Pattern p = Pattern.compile(REGEX);
        Matcher m = p.matcher(INPUT);   // get a matcher object
        int count = 0;
      while(m.find()) {
         count++;
         jTextAreaResultadoBusqueda.append("coincidencia número "+count);
         jTextAreaResultadoBusqueda.append("\ncomienzo: "+m.start());
         jTextAreaResultadoBusqueda.append("\nfin: "+m.end()+"\n");
         
      }
    }//GEN-LAST:event_jButBuscarActionPerformed

    private void jButRemplazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRemplazarActionPerformed
        // TODO add your handling code here:
        jTextAreaResultadoBusqueda.setText("");
        String REGEX = jTextPatron.getText();
        String INPUT = jTextCadena.getText();
        String REPLACE = JOptionPane.showInputDialog("Cadena a remplazar en el texto");
        Pattern p = Pattern.compile(REGEX);
        Matcher m = p.matcher(INPUT); 
        INPUT = m.replaceAll(REPLACE);
        jTextAreaResultadoBusqueda.append(INPUT);
    }//GEN-LAST:event_jButRemplazarActionPerformed

    private void jTextCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCadenaActionPerformed
        // TODO add your handling code here:
        jTextPatron.requestFocus();
    }//GEN-LAST:event_jTextCadenaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButBuscar;
    private javax.swing.JButton jButCoincide;
    private javax.swing.JButton jButRemplazar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaResultadoBusqueda;
    private javax.swing.JTextField jTextCadena;
    private javax.swing.JTextField jTextPatron;
    // End of variables declaration//GEN-END:variables
}
