/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_2019_11_04_aplicacionempleadosherencia;

import java.util.Random;

/**
 *
 * @author admin
 */
public class JFrameRegistro extends javax.swing.JFrame {

    /**
     * Creates new form JFrameRegistro
     */

    //se declara la referencia 
    JFrameMenu frameMenu;
    
    
    public JFrameRegistro(JFrameMenu jfMenu) { //para ponerle la referencia del menu 
        initComponents();
        
        frameMenu = jfMenu; //menu dentro del frame registro 
    }
    public void ocultar(){
    jTextPiezas.setVisible(false);
    jTextPrecio.setVisible(false);
    jTextDias.setVisible(false);
    jTextSueldo.setVisible(false);
    jTextVentas.setVisible(false);
    jTextComision.setVisible(false);
    jTextBono.setVisible(false);
    
    jLabPiezas.setVisible(false);
    jLabPrecio.setVisible(false);
    jLabDias.setVisible(false);
    jLabSueldo.setVisible(false);
    jLabVentas.setVisible(false);
    jLabComision.setVisible(false);
    jLabBono.setVisible(false);
    
    jTextNumero.setText("");
    jTextNombre.setText("");
    jTextPiezas.setText("");
    jTextPrecio.setText("");
    jTextDias.setText("");
    jTextSueldo.setText("");
    jTextVentas.setText("");
    jTextComision.setText("");
    jTextBono.setText("");        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButRegresar = new javax.swing.JButton();
        jRadioEmpleado = new javax.swing.JRadioButton();
        jRadioAdministrativo = new javax.swing.JRadioButton();
        jRadioTaller = new javax.swing.JRadioButton();
        jRadioVentas = new javax.swing.JRadioButton();
        jRadioEjecutivo = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jTextNumero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jLabPiezas = new javax.swing.JLabel();
        jTextPiezas = new javax.swing.JTextField();
        jLabPrecio = new javax.swing.JLabel();
        jTextPrecio = new javax.swing.JTextField();
        jTextSueldo = new javax.swing.JTextField();
        jLabDias = new javax.swing.JLabel();
        jTextDias = new javax.swing.JTextField();
        jLabSueldo = new javax.swing.JLabel();
        jTextComision = new javax.swing.JTextField();
        jLabVentas = new javax.swing.JLabel();
        jTextVentas = new javax.swing.JTextField();
        jLabComision = new javax.swing.JLabel();
        jLabBono = new javax.swing.JLabel();
        jTextBono = new javax.swing.JTextField();
        jButAleatorios = new javax.swing.JButton();
        jButGrabar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabRegistrados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de empleados");
        jLabel1.setOpaque(true);

        jButRegresar.setText("Regresar");
        jButRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegresarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioEmpleado);
        jRadioEmpleado.setText("Empleado");
        jRadioEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEmpleadoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioAdministrativo);
        jRadioAdministrativo.setText("Administrativo");
        jRadioAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioAdministrativoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioTaller);
        jRadioTaller.setText("Taller");
        jRadioTaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioTallerActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioVentas);
        jRadioVentas.setText("Ventas");
        jRadioVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioVentasActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioEjecutivo);
        jRadioEjecutivo.setText("Ejecutivo");
        jRadioEjecutivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEjecutivoActionPerformed(evt);
            }
        });

        jLabel2.setText("Número");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });

        jLabel3.setText("Nombre");

        jLabPiezas.setText("Piezas");

        jLabPrecio.setText("$Piezas");

        jLabDias.setText("Dias T");

        jLabSueldo.setText("Sueldo diario");

        jLabVentas.setText("Ventas totales$");

        jLabComision.setText("% Comisión");

        jLabBono.setText("Bono $");

        jButAleatorios.setText("Aleatorios");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jButGrabar.setText("Grabar");
        jButGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButGrabarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Empleados registrados");

        jLabRegistrados.setBackground(new java.awt.Color(51, 255, 153));
        jLabRegistrados.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabRegistrados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabRegistrados.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabBono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabVentas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(jLabDias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabPiezas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextBono, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextDias, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabSueldo, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                    .addComponent(jLabComision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextNombre)
                                    .addComponent(jTextPrecio)
                                    .addComponent(jTextSueldo)
                                    .addComponent(jTextComision)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 28, Short.MAX_VALUE)
                        .addComponent(jRadioEmpleado)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioTaller)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioAdministrativo)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioVentas)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioEjecutivo)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButAleatorios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButGrabar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabRegistrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButRegresar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioEmpleado)
                    .addComponent(jRadioAdministrativo)
                    .addComponent(jRadioTaller)
                    .addComponent(jRadioVentas)
                    .addComponent(jRadioEjecutivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabPiezas)
                    .addComponent(jTextPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabPrecio)
                    .addComponent(jTextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabDias)
                    .addComponent(jTextDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabSueldo)
                    .addComponent(jTextSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabVentas)
                    .addComponent(jTextVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabComision)
                    .addComponent(jTextComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabBono)
                    .addComponent(jTextBono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabRegistrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButRegresar)
                        .addComponent(jButAleatorios)
                        .addComponent(jButGrabar))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegresarActionPerformed
        // TODO add your handling code here:
                 
         this.dispose();
         frameMenu.getBotonSalida().setText("Exit");
        frameMenu.setVisible(true);
        
        
    }//GEN-LAST:event_jButRegresarActionPerformed

    private void jRadioEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEmpleadoActionPerformed
        // TODO add your handling code here:
        ocultar();
    }//GEN-LAST:event_jRadioEmpleadoActionPerformed

    private void jRadioTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioTallerActionPerformed
        // TODO add your handling code here:
        ocultar();
        jTextPiezas.setVisible(true);
        jTextPrecio.setVisible(true);
        
        jLabPiezas.setVisible(true);
        jLabPrecio.setVisible(true);
        
    }//GEN-LAST:event_jRadioTallerActionPerformed

    private void jRadioAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioAdministrativoActionPerformed
        // TODO add your handling code here:
        ocultar();
        jTextDias.setVisible(true);
        jTextSueldo.setVisible(true);
        jLabDias.setVisible(true);
        jLabSueldo.setVisible(true);


    }//GEN-LAST:event_jRadioAdministrativoActionPerformed

    private void jRadioVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioVentasActionPerformed
        // TODO add your handling code here:
        ocultar();
        
        jTextVentas.setVisible(true);
        jTextComision.setVisible(true);
        
        jLabVentas.setVisible(true);
        jLabComision.setVisible(true);
        
    }//GEN-LAST:event_jRadioVentasActionPerformed

    private void jRadioEjecutivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEjecutivoActionPerformed
        // TODO add your handling code here:
        ocultar();

        jTextVentas.setVisible(true);
        jTextComision.setVisible(true);
        jTextBono.setVisible(true);
        
        jLabVentas.setVisible(true);
        jLabComision.setVisible(true);
        jLabBono.setVisible(true);
    }//GEN-LAST:event_jRadioEjecutivoActionPerformed

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        // TODO add your handling code here:
        MiRandom azar = new MiRandom();
        jTextNumero.setText(frameMenu.getEmpleadosRegistrados()+1+""); //se incrementa en graber para no incrementarlo cada vez que le demos a aleatorio 
        jTextNombre.setText(azar.nextNombreCompleto());
        jTextPiezas.setText(azar.nextInt(100,1000)+"");
        jTextPrecio.setText(azar.nextInt(3,10,0.25)+"");
        jTextDias.setText(azar.nextInt(7,30)+"");
        jTextSueldo.setText(azar.nextInt(110,1200)+"");
        jTextVentas.setText(azar.nextInt(10000,90000,1000)+"");
        jTextComision.setText(azar.nextInt(2,7,0.20)+"");
        jTextBono.setText(azar.nextInt(5000,20000,500)+"");
        
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jButGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButGrabarActionPerformed
        // TODO add your handling code here:
        int num = Integer.parseInt(jTextNumero.getText());
        String nom = jTextNombre.getText();
        
        if(jRadioEmpleado.isSelected()){
        Empleado e = new Empleado(num,nom);
        
        frameMenu.agregarEmpleado(e);
        }
        
        if(jRadioTaller.isSelected()){
        Taller t = new Taller(num,nom,
        Integer.parseInt(jTextPiezas.getText()),
        Double.parseDouble(jTextPrecio.getText()));
        
        frameMenu.agregarEmpleado(t);
        }
        
        if(jRadioAdministrativo.isSelected()){
        Administrativo a = new Administrativo(num,nom,
        Integer.parseInt(jTextDias.getText()), 
        Double.parseDouble(jTextSueldo.getText()));
        
        frameMenu.agregarEmpleado(a);
        }
        
        if(jRadioVentas.isSelected()){
        Ventas v = new Ventas(num,nom, 
        Double.parseDouble(jTextVentas.getText()), 
        Double.parseDouble(jTextComision.getText()));
        
        frameMenu.agregarEmpleado(v);
        }
        
        if(jRadioEjecutivo.isSelected()){
        Ejecutivo e = new Ejecutivo(num,nom,
        Integer.parseInt(jTextDias.getText()), 
        Double.parseDouble(jTextSueldo.getText()), 
        Double.parseDouble(jTextBono.getText()));
        
        frameMenu.agregarEmpleado(e);
        }
        jLabRegistrados.setText(frameMenu.getEmpleadosRegistrados()+"");
    }//GEN-LAST:event_jButGrabarActionPerformed

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
       MiRandom azar = new MiRandom();
       
        for (int i = 1; i <= 7; i++) {
            switch(azar.nextInt(10)){
                case 0: jRadioEmpleado.setSelected(true); 
                break;
                case 5:
                case 9: 
                case 8: 
                case 1: jRadioTaller.setSelected(true); 
                break;
                case 6:
                case 2: jRadioAdministrativo.setSelected(true); 
                break;
                case 7:
                case 3: jRadioVentas.setSelected(true); 
                break;
                case 4: jRadioEjecutivo.setSelected(true); 
                break;
            }
            jButAleatorios.doClick();
            jButGrabar.doClick();
        }
    }//GEN-LAST:event_jLabel2MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameRegistro(new JFrameMenu()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButGrabar;
    private javax.swing.JButton jButRegresar;
    private javax.swing.JLabel jLabBono;
    private javax.swing.JLabel jLabComision;
    private javax.swing.JLabel jLabDias;
    private javax.swing.JLabel jLabPiezas;
    private javax.swing.JLabel jLabPrecio;
    private javax.swing.JLabel jLabRegistrados;
    private javax.swing.JLabel jLabSueldo;
    private javax.swing.JLabel jLabVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioAdministrativo;
    private javax.swing.JRadioButton jRadioEjecutivo;
    private javax.swing.JRadioButton jRadioEmpleado;
    private javax.swing.JRadioButton jRadioTaller;
    private javax.swing.JRadioButton jRadioVentas;
    private javax.swing.JTextField jTextBono;
    private javax.swing.JTextField jTextComision;
    private javax.swing.JTextField jTextDias;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextNumero;
    private javax.swing.JTextField jTextPiezas;
    private javax.swing.JTextField jTextPrecio;
    private javax.swing.JTextField jTextSueldo;
    private javax.swing.JTextField jTextVentas;
    // End of variables declaration//GEN-END:variables
}
