/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applistaenlazadaordenada;

import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class AppListaEnlazadaOrdenadaGUI extends javax.swing.JFrame {

    /**
     * Creates new form AppListaEnlazadaOrdenadaGUI
     */
    DefaultTableModel modeloTabla;
    Random azar;
    
    ListaEnlazadaO listaEnlazada;
    
    String [] nomProd = {"Aceite comestibles","Aderezos","Consome","Crema de cacahuate","Crema para café",
                          "Pure de tomate","Alimento para bebe","Alimento para mascotas","Atole","Avena",
                          "Azúcar","Café","Cereales","Chile piquín","Especias","Flan en polvo",
                          "Formulas infantiles","Gelatinas en polvo/Grenetina","Harina","Harina preparada",
                          "Mole","Sal","Salsas envasadas","Sazonadores","Sopas en sobre","Cajeta","Catsup",
                          "Mayonesa","Mermelada","Miel","Te","Vinagre","Huevo","Pastas"};
    
    public AppListaEnlazadaOrdenadaGUI() {
        initComponents();
        setLocationRelativeTo(null);
        modeloTabla = (DefaultTableModel)jTableProductos.getModel();
       jTableProductos.setShowGrid(true);
        listaEnlazada = new ListaEnlazadaO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ListaEnlazada = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextProducto = new javax.swing.JTextField();
        jLabClave = new javax.swing.JLabel();
        jSpinClave = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabPrecio = new javax.swing.JLabel();
        jSpinPrecio = new javax.swing.JSpinner();
        jButAleatorios = new javax.swing.JButton();
        jButRegistrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jRadioInsertar = new javax.swing.JRadioButton();
        jRadioMostrar = new javax.swing.JRadioButton();
        jRadioBorrar = new javax.swing.JRadioButton();
        jTextBorrar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Producto: ");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Clave:");

        jLabClave.setBackground(new java.awt.Color(255, 255, 255));
        jLabClave.setForeground(new java.awt.Color(0, 0, 0));
        jLabClave.setOpaque(true);

        jSpinClave.setModel(new javax.swing.SpinnerNumberModel(100, 100, 999, 1));
        jSpinClave.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinClaveStateChanged(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Precio:");

        jLabPrecio.setBackground(new java.awt.Color(255, 255, 255));
        jLabPrecio.setForeground(new java.awt.Color(0, 0, 0));
        jLabPrecio.setOpaque(true);

        jSpinPrecio.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        jSpinPrecio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinPrecioStateChanged(evt);
            }
        });

        jButAleatorios.setText("Aleatorios");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jButRegistrar.setText("Registrar");
        jButRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabClave, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinClave, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextProducto))
                .addGap(12, 12, 12))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButAleatorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButRegistrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinPrecio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinClave)
                        .addComponent(jLabel3))
                    .addComponent(jLabClave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButAleatorios)
                    .addComponent(jButRegistrar))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista enlazada", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        ListaEnlazada.add(jRadioInsertar);
        jRadioInsertar.setText("Insertar");
        jRadioInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioInsertarActionPerformed(evt);
            }
        });

        ListaEnlazada.add(jRadioMostrar);
        jRadioMostrar.setText("Mostrar");
        jRadioMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioMostrarActionPerformed(evt);
            }
        });

        ListaEnlazada.add(jRadioBorrar);
        jRadioBorrar.setText("Borrar");
        jRadioBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioMostrar)
                    .addComponent(jRadioInsertar)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jRadioBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jRadioInsertar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioBorrar)
                    .addComponent(jTextBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jTableProductos.setBackground(new java.awt.Color(255, 255, 255));
        jTableProductos.setForeground(new java.awt.Color(0, 0, 0));
        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Producto", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        // TODO add your handling code here:
        Random azar = new Random();
        jTextProducto.setText(nomProd[azar.nextInt(nomProd.length)]);
        jSpinClave.setValue(azar.nextInt(900)+100);
        jSpinPrecio.setValue(azar.nextDouble()*1000);
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jSpinClaveStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinClaveStateChanged
        // TODO add your handling code here:
        jLabClave.setText(jSpinClave.getValue()+"");
    }//GEN-LAST:event_jSpinClaveStateChanged

    private void jSpinPrecioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinPrecioStateChanged
        // TODO add your handling code here:
        jLabPrecio.setText(jSpinPrecio.getValue()+"");
    }//GEN-LAST:event_jSpinPrecioStateChanged

    private void jButRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRegistrarActionPerformed
        // TODO add your handling code here:
        //validar la entrada de datos, que no esten vacios los campos 
        if(jTextProducto.getText().isEmpty() || jSpinClave.getValue().equals("") || jSpinPrecio.getValue().equals("")){
            JOptionPane.showMessageDialog(null, "Entrada no valida\n"
                                              + "Introduce informacion en las casillas");
        }else
            modeloTabla.insertRow(modeloTabla.getRowCount(), new Object[]{jSpinClave.getValue(),jTextProducto.getText(),jSpinPrecio.getValue()});
        
        
        
    }//GEN-LAST:event_jButRegistrarActionPerformed

    private void jRadioInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioInsertarActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<jTableProductos.getRowCount();i++){
        listaEnlazada.Insertar(Integer.valueOf(jTableProductos.getValueAt(i, 0).toString()), 
                                               jTableProductos.getValueAt(i, 1).toString(), 
                               Double.valueOf(jTableProductos.getValueAt(i, 2).toString()));
        }
    }//GEN-LAST:event_jRadioInsertarActionPerformed

    private void jRadioMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioMostrarActionPerformed
        // TODO add your handling code here:
        //limpiar la tabla
        modeloTabla.setRowCount(0);
        listaEnlazada.Mostrar(modeloTabla);
    }//GEN-LAST:event_jRadioMostrarActionPerformed

    private void jRadioBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBorrarActionPerformed
        // TODO add your handling code here:

        int clave = Integer.parseInt(jTextBorrar.getText());
        listaEnlazada.Borrar(clave);
        
    }//GEN-LAST:event_jRadioBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppListaEnlazadaOrdenadaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppListaEnlazadaOrdenadaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppListaEnlazadaOrdenadaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppListaEnlazadaOrdenadaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppListaEnlazadaOrdenadaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ListaEnlazada;
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButRegistrar;
    private javax.swing.JLabel jLabClave;
    private javax.swing.JLabel jLabPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioBorrar;
    private javax.swing.JRadioButton jRadioInsertar;
    private javax.swing.JRadioButton jRadioMostrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinClave;
    private javax.swing.JSpinner jSpinPrecio;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTextField jTextBorrar;
    private javax.swing.JTextField jTextProducto;
    // End of variables declaration//GEN-END:variables
}
