/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_2019_10_23_tarjetaasistencia;

import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aa530
 */
public class JFrameTarjeta extends javax.swing.JFrame {

    /**
     * Creates new form JFrameTarjeta
     */
    DefaultTableModel modelo;
    public JFrameTarjeta() {
        initComponents();
        
        modelo = (DefaultTableModel)jTableEmpleados.getModel();   
        
       jTableEmpleados.setShowGrid(true); // pone la cuadricula en la tabla     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jButCalcular = new javax.swing.JButton();
        jSpinEmpleados = new javax.swing.JSpinner();
        jButAleatorios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButArregloFrame = new javax.swing.JButton();
        jButArregloEncapsulado = new javax.swing.JButton();
        jButArregloParalelos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Empleado", "Hor", "Min", "Seg", "Hor", "Min", "Seg", "tiempo trabajado"
            }
        ));
        jScrollPane1.setViewportView(jTableEmpleados);
        if (jTableEmpleados.getColumnModel().getColumnCount() > 0) {
            jTableEmpleados.getColumnModel().getColumn(0).setPreferredWidth(150);
            jTableEmpleados.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTableEmpleados.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTableEmpleados.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTableEmpleados.getColumnModel().getColumn(4).setPreferredWidth(50);
            jTableEmpleados.getColumnModel().getColumn(5).setPreferredWidth(50);
            jTableEmpleados.getColumnModel().getColumn(6).setPreferredWidth(50);
            jTableEmpleados.getColumnModel().getColumn(7).setPreferredWidth(150);
        }

        jButCalcular.setText("Calcular");
        jButCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalcularActionPerformed(evt);
            }
        });

        jSpinEmpleados.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinEmpleadosStateChanged(evt);
            }
        });

        jButAleatorios.setText("Aleatorios");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jLabel1.setText("Total");

        jLabTotal.setBackground(new java.awt.Color(255, 255, 102));
        jLabTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabTotal.setOpaque(true);

        jLabel3.setText("Numero de empleados");

        jLabel2.setBackground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("HORARIO DE ENTRADA");
        jLabel2.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("HORARIO DE SALIDA");
        jLabel4.setOpaque(true);

        jButArregloFrame.setText("Arreglo en  Frame");
        jButArregloFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButArregloFrameActionPerformed(evt);
            }
        });

        jButArregloEncapsulado.setText("Arreglo encapsulado");
        jButArregloEncapsulado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButArregloEncapsuladoActionPerformed(evt);
            }
        });

        jButArregloParalelos.setText("Arreglos paralelos");
        jButArregloParalelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButArregloParalelosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButArregloFrame)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(99, 99, 99)
                                        .addComponent(jButCalcular)
                                        .addGap(37, 37, 37)
                                        .addComponent(jButAleatorios))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(154, 154, 154)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel4))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(227, 227, 227))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButArregloParalelos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButArregloEncapsulado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButCalcular)
                    .addComponent(jButAleatorios))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButArregloFrame))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButArregloEncapsulado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButArregloParalelos)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinEmpleadosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinEmpleadosStateChanged
         modelo.setRowCount((int)jSpinEmpleados.getValue());
    }//GEN-LAST:event_jSpinEmpleadosStateChanged

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
      Random azar = new Random();
        

        for (int r = 0; r < modelo.getRowCount(); r++) {
        modelo.setValueAt(Nombres.nextNombreCompleto(), r, 0);
       
        modelo.setValueAt(7+azar.nextInt(4),r,1);
        modelo.setValueAt(azar.nextInt(60),r,2);
        modelo.setValueAt(azar.nextInt(60),r,3);
        
        modelo.setValueAt(14+azar.nextInt(4),r,4);
        modelo.setValueAt(azar.nextInt(60),r,5);
        modelo.setValueAt(azar.nextInt(60),r,6);
        modelo.setValueAt(null,r,7);
        }    
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jButCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalcularActionPerformed
        // TODO add your handling code here:
        Horario entrada = new Horario();
        Horario salida = new Horario();
        Horario tiempoTrabajado;
        Horario tiempoTotal = new Horario();
        
        for (int r = 0; r < modelo.getRowCount(); r++) {
        entrada.setHoras(Integer.parseInt(modelo.getValueAt(r, 1)+""));       
        entrada.setMinutos(Integer.parseInt(modelo.getValueAt(r, 2)+""));         
        entrada.setSegundos(Integer.parseInt(modelo.getValueAt(r, 3)+""));         
        
        salida.setHoras(Integer.parseInt(modelo.getValueAt(r, 4)+""));       
        salida.setMinutos(Integer.parseInt(modelo.getValueAt(r, 5)+""));         
        salida.setSegundos(Integer.parseInt(modelo.getValueAt(r, 6)+"")); 
       
        tiempoTrabajado = salida.resta(entrada);
        modelo.setValueAt(tiempoTrabajado, r, 7);
        
        tiempoTotal = tiempoTotal.suma(tiempoTrabajado);
        
      
        }
          jLabTotal.setText(tiempoTotal+"");
    }//GEN-LAST:event_jButCalcularActionPerformed

    private void jButArregloFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButArregloFrameActionPerformed
        // TODO add your handling code here:
        Empleado [] lista = new Empleado[modelo.getRowCount()]; 
       
        for (int r = 0; r < lista.length; r++){
        Horario entrada = new Horario();
        Horario salida = new Horario();
        
        entrada.setHoras(Integer.parseInt(modelo.getValueAt(r, 1)+""));       
        entrada.setMinutos(Integer.parseInt(modelo.getValueAt(r, 2)+""));         
        entrada.setSegundos(Integer.parseInt(modelo.getValueAt(r, 3)+""));         
        
        salida.setHoras(Integer.parseInt(modelo.getValueAt(r, 4)+""));       
        salida.setMinutos(Integer.parseInt(modelo.getValueAt(r, 5)+""));         
        salida.setSegundos(Integer.parseInt(modelo.getValueAt(r, 6)+"")); 
       
        lista[r] = new Empleado(modelo.getValueAt(r,0)+"",entrada,salida);  
        }
        for (int i = 0; i < lista.length-1; i++) 
            for (int j = i+1; j < lista.length; j++) 
                if(lista[i].tiempoTrabajado().segundosTotales() > 
                        lista[j].tiempoTrabajado().segundosTotales())
                {
                Empleado aux = lista[i];
                lista[i] = lista[j];
                lista[j] = aux;
                }
        
        for (int r = 0; r < lista.length; r++) {
            modelo.setValueAt(lista[r].getNombre(), r, 0);
            modelo.setValueAt(lista[r].getEntrada().getHoras(),r,1);
            modelo.setValueAt(lista[r].getEntrada().getMinutos(),r,2);
            modelo.setValueAt(lista[r].getEntrada().getSegundos(),r,3);

            modelo.setValueAt(lista[r].getSalida().getHoras(),r,1);
            modelo.setValueAt(lista[r].getSalida().getMinutos(),r,2);
            modelo.setValueAt(lista[r].getSalida().getSegundos(),r,3);
            
            modelo.setValueAt(lista[r].tiempoTrabajado(),r,7);
        }
    }//GEN-LAST:event_jButArregloFrameActionPerformed

    private void jButArregloEncapsuladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButArregloEncapsuladoActionPerformed
        // TODO add your handling code here:
        Empresa lala = new Empresa(modelo.getRowCount());
        
        for (int r = 0; r < modelo.getRowCount(); r++){
        Horario entrada = new Horario();
        Horario salida = new Horario();
        
        entrada.setHoras(Integer.parseInt(modelo.getValueAt(r, 1)+""));       
        entrada.setMinutos(Integer.parseInt(modelo.getValueAt(r, 2)+""));         
        entrada.setSegundos(Integer.parseInt(modelo.getValueAt(r, 3)+""));         
        
        salida.setHoras(Integer.parseInt(modelo.getValueAt(r, 4)+""));       
        salida.setMinutos(Integer.parseInt(modelo.getValueAt(r, 5)+""));         
        salida.setSegundos(Integer.parseInt(modelo.getValueAt(r, 6)+"")); 
       
        
        Empleado emp = new Empleado(modelo.getValueAt(r,0)+"",entrada,salida);  
        
        lala.setEmpleado(emp, r);
        }
        
        lala.ordenar();
         for (int r = 0; r < modelo.getRowCount(); r++) {
            modelo.setValueAt(lala.getEmpleado(r).getNombre(), r, 0);
            modelo.setValueAt(lala.getEmpleado(r).getEntrada().getHoras(),r,1);
            modelo.setValueAt(lala.getEmpleado(r).getEntrada().getMinutos(),r,2);
            modelo.setValueAt(lala.getEmpleado(r).getEntrada().getSegundos(),r,3);

            modelo.setValueAt(lala.getEmpleado(r).getSalida().getHoras(),r,1);
            modelo.setValueAt(lala.getEmpleado(r).getSalida().getMinutos(),r,2);
            modelo.setValueAt(lala.getEmpleado(r).getSalida().getSegundos(),r,3);
            
            modelo.setValueAt(lala.getEmpleado(r).tiempoTrabajado(),r,7);
        }
        
    }//GEN-LAST:event_jButArregloEncapsuladoActionPerformed

    private void jButArregloParalelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButArregloParalelosActionPerformed
        // TODO add your handling code here:
        
        String [] nombres = new String[modelo.getRowCount()];
        Horario [] entradas = new Horario[nombres.length];
        Horario [] salidas = new Horario[nombres.length];
        Horario [] tiempoTrab = new Horario[nombres.length];
        
        for (int r = 0; r < modelo.getRowCount(); r++){
        Horario entrada = new Horario();
        Horario salida = new Horario();
        
        entrada.setHoras(Integer.parseInt(modelo.getValueAt(r, 1)+""));       
        entrada.setMinutos(Integer.parseInt(modelo.getValueAt(r, 2)+""));         
        entrada.setSegundos(Integer.parseInt(modelo.getValueAt(r, 3)+""));         
        
        salida.setHoras(Integer.parseInt(modelo.getValueAt(r, 4)+""));       
        salida.setMinutos(Integer.parseInt(modelo.getValueAt(r, 5)+""));         
        salida.setSegundos(Integer.parseInt(modelo.getValueAt(r, 6)+"")); 
        
        nombres [r] = modelo.getValueAt(r,0)+"";
        entradas[r] = entrada;
        salidas [r] = salida;
        tiempoTrab[r] = salida.resta(entrada);
        }
        
        for (int i = 0; i < tiempoTrab.length-1; i++) 
            for (int j = i+1; j < tiempoTrab.length; j++) 
                if(tiempoTrab[i].segundosTotales()>tiempoTrab[j].segundosTotales()){
                Horario aux = tiempoTrab[i];
                tiempoTrab[i] = tiempoTrab[j];
                tiempoTrab[j] = aux;
                
                aux = entradas[i]; 
                entradas[i] = entradas[j];
                entradas[j] = aux;
                
                aux = salidas[i]; 
                salidas[i] = salidas[j];
                salidas[j] = aux;
               
                String auxn = nombres[i];
                nombres[i] = nombres[j];
                nombres[j] = auxn;
                }
            
        for (int r = 0; r < modelo.getRowCount(); r++) {
         modelo.setValueAt(nombres[r], r, 0);
         modelo.setValueAt(entradas[r].getHoras(), r, 1);
         modelo.setValueAt(entradas[r].getMinutos(), r, 2);
         modelo.setValueAt(entradas[r].getSegundos(), r, 3);
        
         modelo.setValueAt(salidas[r].getHoras(), r, 4);
         modelo.setValueAt(salidas[r].getMinutos(), r, 5);
         modelo.setValueAt(salidas[r].getSegundos(), r, 6);
         
         modelo.setValueAt(tiempoTrab[r], r, 7);
        }
        
    }//GEN-LAST:event_jButArregloParalelosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTarjeta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButArregloEncapsulado;
    private javax.swing.JButton jButArregloFrame;
    private javax.swing.JButton jButArregloParalelos;
    private javax.swing.JButton jButCalcular;
    private javax.swing.JLabel jLabTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinEmpleados;
    private javax.swing.JTable jTableEmpleados;
    // End of variables declaration//GEN-END:variables
}
