
import pa_2019_08_21_aplicacionconovisual.Cono;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class AplicacionCono extends javax.swing.JFrame {

    /**
     * Creates new form AplicacionCono
     */
    public AplicacionCono() {
        initComponents();
    }

    // definición de funciones
    public double volumenCono(double r, double h)  
    {
//       double v;
//       v = Math.PI * Math.pow(r,2)*h/3;
//       return v;
    return Math.PI*Math.pow (r,2)+h/3;
    }
    
    public double generatriz(double r, double h)
    {
    return Math.sqrt(Math.pow(r,2) + Math.pow(h,2));
    }
    
    public double areaCono(double r, double h)
    {
    return Math.PI*r*(r+generatriz(r,h));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        Radio = new java.awt.Label();
        Altura = new java.awt.Label();
        jTextRadio = new java.awt.TextField();
        jTextAltura = new java.awt.TextField();
        Volumen = new java.awt.Label();
        Area = new java.awt.Label();
        jLabVolumen = new java.awt.Label();
        jLabArea = new java.awt.Label();
        jButObjeto = new javax.swing.JButton();
        jButCalcular = new javax.swing.JButton();
        jButFunciones = new javax.swing.JButton();
        jButAleatorio = new javax.swing.JButton();
        jButBorrar = new javax.swing.JButton();

        textField1.setText("textField1");

        textField2.setText("textField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Radio.setBackground(new java.awt.Color(255, 255, 153));
        Radio.setText("Radio");

        Altura.setBackground(new java.awt.Color(255, 255, 153));
        Altura.setText("Altura");

        jTextRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRadioActionPerformed(evt);
            }
        });

        Volumen.setBackground(new java.awt.Color(255, 255, 153));
        Volumen.setText("Volumen");

        Area.setBackground(new java.awt.Color(255, 255, 153));
        Area.setText("Area");

        jLabVolumen.setBackground(new java.awt.Color(153, 255, 204));

        jLabArea.setBackground(new java.awt.Color(153, 255, 204));

        jButObjeto.setBackground(new java.awt.Color(204, 255, 102));
        jButObjeto.setText("Objeto");
        jButObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButObjetoActionPerformed(evt);
            }
        });

        jButCalcular.setBackground(new java.awt.Color(255, 255, 0));
        jButCalcular.setText("Calcular");
        jButCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalcularActionPerformed(evt);
            }
        });

        jButFunciones.setBackground(new java.awt.Color(0, 255, 255));
        jButFunciones.setText("Funciones");
        jButFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButFuncionesActionPerformed(evt);
            }
        });

        jButAleatorio.setBackground(new java.awt.Color(255, 153, 153));
        jButAleatorio.setText("Aleatorio");
        jButAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatorioActionPerformed(evt);
            }
        });

        jButBorrar.setBackground(new java.awt.Color(153, 153, 255));
        jButBorrar.setText("Borrar");
        jButBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Area, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Volumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Altura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Radio, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButObjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButAleatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextAltura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabArea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabVolumen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButAleatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButFunciones, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Radio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Volumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRadioActionPerformed

    private void jButObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButObjetoActionPerformed
        // TODO add your handling code here:
       
        //Declaración de variable 
        double radio, altura, volumen, area, generatriz;
        
        //Entada de datos
        try
        {
        radio  = Double.parseDouble(jTextRadio.getText());
        altura = Double.parseDouble(jTextAltura.getText());
        }
        catch(Exception ex)
        {
         JOptionPane.showMessageDialog(rootPane, "Datos de entrada incorrectos... ");
         return;
        }
     
        Cono cualquiera = new Cono(radio,altura);
        
        jLabArea.setText(cualquiera.area()+"");
        jLabVolumen.setText(cualquiera.volumen()+"");
        
        jLabArea.setBackground(jButObjeto.getBackground());
        jLabVolumen.setBackground(jButObjeto.getBackground());
        
    }//GEN-LAST:event_jButObjetoActionPerformed

    private void jButCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalcularActionPerformed
        // TODO add your handling code here:
          //Declaración de variable 
        double radio, altura, volumen, area, generatriz;
        
        //Entada de datos
        try
        {
        radio  = Double.parseDouble(jTextRadio.getText());
        altura = Double.parseDouble(jTextAltura.getText());
        }
        catch(Exception ex)
        {
         JOptionPane.showMessageDialog(rootPane, "Datos de entrada incorrectos... ");
         return;
        }
        //Proceso de datos
        volumen    = Math.PI * Math.pow(radio,2) * altura/3;
        generatriz = Math.sqrt(Math.pow(radio,2) + Math.pow(altura, 2));
        area       = Math.PI * radio * (radio + generatriz);

        //salida
        jLabArea.setText(area+"");
        jLabVolumen.setText(volumen+"");
        
        jLabArea.setBackground(jButCalcular.getBackground());
        jLabVolumen.setBackground(jButCalcular.getBackground());


       
    }//GEN-LAST:event_jButCalcularActionPerformed

    private void jButFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButFuncionesActionPerformed
        // TODO add your handling code here:
        
        
        //Declaración de variable 
        double radio, altura, volumen, area, generatriz;
        
        //Entada de datos
        try
        {
        radio  = Double.parseDouble(jTextRadio.getText());
        altura = Double.parseDouble(jTextAltura.getText());
        }
        catch(Exception ex)
        {
         JOptionPane.showMessageDialog(rootPane, "Datos de entrada incorrectos... ");
         return;
        }
        
        //Proceso de datos
        volumen    = Math.PI * Math.pow(radio,2) * altura/3;
        generatriz = Math.sqrt(Math.pow(radio,2) + Math.pow(altura, 2));
        area       = Math.PI * radio * (radio + generatriz);
        
     
        
        //salida
//        jLabArea.setText(areaCono(radio,altura)+"");
//        jLabVolumen.setText(""+volumenCono(radio,altura));
        
        jLabArea.setText(area+"");
        jLabVolumen.setText(volumen+"");
        
        jLabArea.setBackground(jButFunciones.getBackground());
        jLabVolumen.setBackground(jButFunciones.getBackground());
        
    }//GEN-LAST:event_jButFuncionesActionPerformed

    private void jButAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatorioActionPerformed
        // TODO add your handling code here:
        
            
    Random azar = new Random();
    
    jTextRadio.setText(azar.nextInt(100)+"");
    int altura = Integer.parseInt(jTextRadio.getText())+azar.nextInt(100);

    jTextRadio.setText(azar.nextInt(100)+"");
    jTextAltura.setText(azar.nextInt(500)+"");
    jLabVolumen.setText("");
    jLabArea.setText("");

    
            
//        jtextradio.setText(altura+"");
    
    }//GEN-LAST:event_jButAleatorioActionPerformed

    private void jButBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButBorrarActionPerformed
        // TODO add your handling code here:
       jTextRadio.setText("");
       jTextAltura.setText("");
       jLabArea.setText("");
       jLabVolumen.setText("");
    }//GEN-LAST:event_jButBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplicacionCono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplicacionCono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplicacionCono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplicacionCono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplicacionCono().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Altura;
    private java.awt.Label Area;
    private java.awt.Label Radio;
    private java.awt.Label Volumen;
    private javax.swing.JButton jButAleatorio;
    private javax.swing.JButton jButBorrar;
    private javax.swing.JButton jButCalcular;
    private javax.swing.JButton jButFunciones;
    private javax.swing.JButton jButObjeto;
    private java.awt.Label jLabArea;
    private java.awt.Label jLabVolumen;
    private java.awt.TextField jTextAltura;
    private java.awt.TextField jTextRadio;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    // End of variables declaration//GEN-END:variables
}
