/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_2019_10_02_aplicacionvector;

import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class JFrameResultante extends javax.swing.JFrame {

    /**
     * Creates new form JFrameResultante
     */
    public JFrameResultante() {
        initComponents();
        jTableVectores.setShowGrid(true);
        jTableResultante.setShowGrid(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResultante = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSpinVectores = new javax.swing.JSpinner();
        jButAleatorios = new javax.swing.JButton();
        jButResultante = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVectores = new javax.swing.JTable();
        jButEjemplo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableResultante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Magnitud", "Angulo", "X", "Y"
            }
        ));
        jScrollPane1.setViewportView(jTableResultante);

        jLabel1.setText("No. de Vectores");

        jSpinVectores.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinVectoresStateChanged(evt);
            }
        });

        jButAleatorios.setText("Aleatorios");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jButResultante.setText("Resultante");
        jButResultante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButResultanteActionPerformed(evt);
            }
        });

        jTableVectores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Magnitud", "Angulo", "X", "Y"
            }
        ));
        jScrollPane2.setViewportView(jTableVectores);

        jButEjemplo.setText("Ejemplo");
        jButEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemploActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinVectores, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButAleatorios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButResultante)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButEjemplo)
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jSpinVectores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButAleatorios))
                    .addComponent(jButResultante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButEjemplo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButResultanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButResultanteActionPerformed
        // TODO add your handling code here:
        
        Vector renglon;
        Vector resultante = new Vector();
       
        for (int r = 0; r < jTableVectores.getRowCount(); r++){
            if(jTableResultante.getValueAt(r, 0) == null)
            {
                //el usuario capturo x e y 
                renglon = new Vector();
                renglon.setXY(Double.parseDouble(jTableVectores.getValueAt(r, 2)+""), 
                              Double.parseDouble(jTableVectores.getValueAt(r, 3)+""));
                
                jTableVectores.setValueAt(renglon.getMagnitud(), r, 0);
                jTableVectores.setValueAt(renglon.getAngulo(), r, 1);
        }
            else{
            //el usuario capturo magnitud y angulo 
            renglon = new Vector(Double.parseDouble(jTableVectores.getValueAt(r, 0)+""),
                                 Double.parseDouble(jTableVectores.getValueAt(r, 1)+""));
           jTableVectores.setValueAt(renglon.getX(), r, 2);
           jTableVectores.setValueAt(renglon.getY(), r, 3);
            }
            resultante.suma(renglon);
        }
        jTableResultante.setValueAt(resultante.getMagnitud(), 0, 0);
        jTableResultante.setValueAt(resultante.getAngulo(), 0, 1);
        jTableResultante.setValueAt(resultante.getX(), 0, 2);
        jTableResultante.setValueAt(resultante.getY(), 0, 3);



    }//GEN-LAST:event_jButResultanteActionPerformed

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        // TODO add your handling code here
        Random azar = new Random();
        for(int r=0;r<jTableVectores.getRowCount();r++){
           for(int c=0;c<jTableVectores.getColumnCount();c++)
               jTableVectores.setValueAt(null,r,c);
           
        if(azar.nextBoolean()){
        //llenamos magnitud y angulo 
        jTableVectores.setValueAt(azar.nextInt(1000), r, 0); //magnitud 
        jTableVectores.setValueAt(azar.nextInt(360),r,1);    //angulo
        }
        else{
        // llenamos x e y 
        jTableVectores.setValueAt(azar.nextInt(1000), r, 2); //x
        jTableVectores.setValueAt(azar.nextInt(1000), r, 3); //x
        } 
        }
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jSpinVectoresStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinVectoresStateChanged
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel)jTableVectores.getModel();
        modelo.setRowCount((int) jSpinVectores.getValue());
    }//GEN-LAST:event_jSpinVectoresStateChanged

    private void jButEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemploActionPerformed
        // TODO add your handling code here:
        jSpinVectores.setValue(2);
        jTableVectores.setValueAt(90, 0, 0);
        jTableVectores.setValueAt(20, 0, 1);
        jTableVectores.setValueAt(68.8291, 1, 2);
        jTableVectores.setValueAt(98.2982, 1, 3);
  

    }//GEN-LAST:event_jButEjemploActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameResultante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameResultante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameResultante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameResultante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameResultante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButEjemplo;
    private javax.swing.JButton jButResultante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinVectores;
    private javax.swing.JTable jTableResultante;
    private javax.swing.JTable jTableVectores;
    // End of variables declaration//GEN-END:variables
}
