/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_19130519_proyecto_04;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class PA_19130519_Frame_01 extends javax.swing.JFrame {

    /**
     * Creates new form PA_19130519_Frame_01
     */
    DefaultTableModel modelo;
    Graphics dibujar ;
    int [] x;
    int [] y;
    JFileChooser jfch = new JFileChooser();
    
    public PA_19130519_Frame_01() {
        initComponents();
        modelo = (DefaultTableModel)jTablePoligono.getModel();
        jSpinLineas.setValue(0);
        jTablePoligono.setShowGrid(true);
    }
     
    public void dibujarPoligono(int [] x, int [] y, Component componente){
     
        dibujar = componente.getGraphics();
        dibujar.setColor(componente.getBackground());
        dibujar.fillRect(5, 5, componente.getWidth(), componente.getHeight());
                  
        if(jTextColor.getText().equals("1")){
        dibujar.setColor(Color.black);
        }
        if(jTextColor.getText().equals("2")){
        dibujar.setColor(Color.green);
        }
        if(jTextColor.getText().equals("3")){
        dibujar.setColor(Color.red);
        }
        if(jTextColor.getText().equals("4")){
        dibujar.setColor(Color.blue);
        }
        if(jTextColor.getText().equals("5")){
        dibujar.setColor(Color.gray);
        }
        if(jTextColor.getText().equals("6")){
        dibujar.setColor(Color.orange);
        }
        if(jTextColor.getText().equals("7")){
        dibujar.setColor(Color.yellow);
        }
        if(jTextColor.getText().equals("8")){
        dibujar.setColor(Color.magenta);
        }
        
        dibujar.drawPolygon(x, y, modelo.getRowCount());
        
        int xCenter = componente.getWidth() / 2;
        int yCenter = componente.getHeight() / 2;
        dibujar.setColor(Color.black);
        dibujar.drawString(jTextIdentificador.getText(), xCenter, yCenter);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePoligono = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSpinLineas = new javax.swing.JSpinner();
        jPanelPoligono = new javax.swing.JPanel();
        jButDibujar = new javax.swing.JButton();
        jButEjemplo = new javax.swing.JButton();
        jButAleatorio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextIdentificador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextColor = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuNuevo = new javax.swing.JMenuItem();
        jMenuAbrir = new javax.swing.JMenuItem();
        jMenuGuardar = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setText("Nombre: Roberto Esquivel Troncoso");

        jLabel10.setText("No de control: 19130519");

        jLabel11.setText("No de proyecto: 4");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PA_19130519_Proyecto_04.png"))); // NOI18N

        jTablePoligono.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Posición x", "Posición y"
            }
        ));
        jScrollPane1.setViewportView(jTablePoligono);

        jLabel2.setText("Lineas");

        jSpinLineas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinLineasStateChanged(evt);
            }
        });

        jPanelPoligono.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelPoligonoLayout = new javax.swing.GroupLayout(jPanelPoligono);
        jPanelPoligono.setLayout(jPanelPoligonoLayout);
        jPanelPoligonoLayout.setHorizontalGroup(
            jPanelPoligonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanelPoligonoLayout.setVerticalGroup(
            jPanelPoligonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButDibujar.setText("Grabar");
        jButDibujar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDibujarActionPerformed(evt);
            }
        });

        jButEjemplo.setText("Ejemplo");
        jButEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemploActionPerformed(evt);
            }
        });

        jButAleatorio.setText("Aleatorios");
        jButAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatorioActionPerformed(evt);
            }
        });

        jLabel3.setText("Identificador");

        jLabel4.setText("Color");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("1 = Negro\n2 = Verde\n3 = Rojo\n4 = Azul \n5 = Gris \n6 = Naranja \n7 = Amarillo \n8 = Magneta");
        jScrollPane2.setViewportView(jTextArea1);

        jMenu1.setText("Archivo");

        jMenuNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nuevo.png"))); // NOI18N
        jMenuNuevo.setText("Nuevo");
        jMenuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuNuevo);

        jMenuAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Abrir.png"))); // NOI18N
        jMenuAbrir.setText("Abrir");
        jMenuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAbrir);

        jMenuGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Guardar.png"))); // NOI18N
        jMenuGuardar.setText("Guardar");
        jMenuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuGuardar);

        jMenuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelPoligono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextColor, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinLineas, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButDibujar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButEjemplo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButAleatorio)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButDibujar)
                            .addComponent(jButEjemplo)
                            .addComponent(jButAleatorio)
                            .addComponent(jLabel2)
                            .addComponent(jSpinLineas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addComponent(jPanelPoligono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNuevoActionPerformed
        // TODO add your handling code here:
         jSpinLineas.setValue(0);
         jTextIdentificador.setText("");
         jTextColor.setText("");
         dibujarPoligono(x, y, jPanelPoligono);
    }//GEN-LAST:event_jMenuNuevoActionPerformed

    private void jButDibujarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDibujarActionPerformed
        // TODO add your handling code here:
        
         x = new int[modelo.getRowCount()];
         y = new int[modelo.getRowCount()];
        int i=0;
        for(int c=0;c<modelo.getRowCount();c++){
        x[i] = Integer.parseInt(modelo.getValueAt(c, 0)+"");
        y[i] = Integer.parseInt(modelo.getValueAt(c, 1)+"");
        i++;
        }
 
        dibujarPoligono(x, y, jPanelPoligono);
    }//GEN-LAST:event_jButDibujarActionPerformed

    private void jSpinLineasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinLineasStateChanged
        // TODO add your handling code here:
       // lineas del poligono
     modelo.setRowCount((int)jSpinLineas.getValue());
    }//GEN-LAST:event_jSpinLineasStateChanged

    private void jButEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemploActionPerformed
        // TODO add your handling code here:
        Random azar = new Random();
        jSpinLineas.setValue(6);
        modelo.setValueAt("17", 0, 0); // cordenadas x
        modelo.setValueAt("112", 1, 0);
        modelo.setValueAt("207", 2, 0);
        modelo.setValueAt("209", 3, 0);
        modelo.setValueAt("113", 4, 0);
        modelo.setValueAt("15",  5, 0);
        
        modelo.setValueAt("51",  0, 1); //cordenadas y
        modelo.setValueAt("12",  1, 1);
        modelo.setValueAt("50",  2, 1);
        modelo.setValueAt("126", 3, 1);
        modelo.setValueAt("164", 4, 1);
        modelo.setValueAt("126", 5, 1);
        
        jTextIdentificador.setText(azar.nextInt(100)+"");
        jTextColor.setText(1+azar.nextInt(7)+"");
    }//GEN-LAST:event_jButEjemploActionPerformed

    private void jButAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatorioActionPerformed
        // TODO add your handling code here:
        Random azar = new Random();
        jSpinLineas.setValue(5);
        modelo.setValueAt(10+azar.nextInt(11),0,0);// cordenadas x
        modelo.setValueAt(90+azar.nextInt(21), 1, 0);
        modelo.setValueAt(170+azar.nextInt(21),2, 0);
        modelo.setValueAt(140+azar.nextInt(21), 3, 0);
        modelo.setValueAt(40+azar.nextInt(20), 4, 0);
        
        modelo.setValueAt(50+azar.nextInt(20),  0, 1); //cordenadas y
        modelo.setValueAt(15+azar.nextInt(8),  1, 1);
        modelo.setValueAt(50+azar.nextInt(20),  2, 1);
        modelo.setValueAt(120+azar.nextInt(22), 3, 1);
        modelo.setValueAt(120+azar.nextInt(22), 4, 1);
        
        jTextIdentificador.setText(azar.nextInt(100)+"");
        jTextColor.setText(1+azar.nextInt(7)+"");
    }//GEN-LAST:event_jButAleatorioActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGuardarActionPerformed
        // TODO add your handling code here:

        if(jfch.showSaveDialog(jMenu1)!=0)
        return;

        FileOutputStream fos=null;
        DataOutputStream dos=null;
        try {

            fos = new FileOutputStream(jfch.getSelectedFile());
            dos = new DataOutputStream(fos);

            dos.writeInt(modelo.getRowCount());

            //recorrer el jTable
            for(int r=0;r<modelo.getRowCount();r++){
                dos.writeInt(Integer.parseInt(modelo.getValueAt(r, 0)+""));
                dos.writeInt(Integer.parseInt(modelo.getValueAt(r, 1)+""));
            }
            dos.writeUTF(jTextIdentificador.getText());
            dos.writeUTF(jTextColor.getText());

        } catch (FileNotFoundException ex) {
            Logger.getLogger(PA_19130519_Frame_01.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PA_19130519_Frame_01.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            try {
                if(dos!=null)
                dos.close();
                if(fos!=null)
                fos.close();
            } catch (IOException ex) {
                Logger.getLogger(PA_19130519_Frame_01.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jMenuGuardarActionPerformed

    private void jMenuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAbrirActionPerformed
        // TODO add your handling code here:
        if(jfch.showSaveDialog(jMenu1)!=0)
        return;

        FileInputStream fis = null;
        DataInputStream dis = null;

        try {
            fis = new FileInputStream(jfch.getSelectedFile());
            dis = new DataInputStream(fis);

            int n = dis.readInt();

            jSpinLineas.setValue(n);

            for(int r=0;r<modelo.getRowCount();r++){
                modelo.setValueAt(dis.readInt(), r, 0);
                modelo.setValueAt(dis.readInt(), r, 1);
            }
            jTextIdentificador.setText(dis.readUTF());
            jTextColor.setText(dis.readUTF());

        } catch (FileNotFoundException ex) {
            Logger.getLogger(PA_19130519_Frame_01.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PA_19130519_Frame_01.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            try {
                if(dis!=null)
                dis.close();
                if(fis!=null)
                fis.close();
            } catch (IOException ex) {
                Logger.getLogger(PA_19130519_Frame_01.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jMenuAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PA_19130519_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PA_19130519_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PA_19130519_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PA_19130519_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PA_19130519_Frame_01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButAleatorio;
    private javax.swing.JButton jButDibujar;
    private javax.swing.JButton jButEjemplo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuAbrir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuGuardar;
    private javax.swing.JMenuItem jMenuNuevo;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JPanel jPanelPoligono;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinLineas;
    private javax.swing.JTable jTablePoligono;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextColor;
    private javax.swing.JTextField jTextIdentificador;
    // End of variables declaration//GEN-END:variables
}
