/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_2019_11_21_aplicaciondibujo;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author admin
 */
public class JFrameDibujo2 extends javax.swing.JFrame {

    /**
     * Creates new form JFrameDibujo
     */
    public JFrameDibujo2() {
        initComponents();
    }

        public void dibujar(int x, Component componente){
        Graphics papel = getGraphics(); //sirbe para dibujar en el frame figuras basicas 
        
        // "borrando"
        papel.setColor(this.getBackground());
        papel.fillRect(5, 70, this.getWidth()-10, 135);
        
        papel.setColor(Color.blue);
        papel.drawRect(x+15, 70, 100, 50);
        papel.drawRect(x+15, 120, 150, 40);
        papel.setColor(Color.green);
        papel.fillRect(x+20,75,90,40);
        papel.setColor(Color.yellow);
        papel.fillRect(x+20,125,140,30);
        papel.setColor(Color.white);
        papel.drawString("Tec Laguna", x+30, 100);
        papel.setColor(Color.red);
        papel.drawLine(x+15, 130, x+165, 130);
        papel.drawLine(x+15, 140, x+165, 140);
        papel.drawLine(x+15, 150, x+165, 150);
        papel.setColor(Color.black);
        papel.fillOval(x+35, 160, 20, 20);        
        papel.fillOval(x+125, 160, 20, 20);
        
        try {
            Thread.sleep(100);
        } catch (InterruptedException ex) {
            Logger.getLogger(JFrameDibujo2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void dibujarVertical(int y, Component componente){
        Graphics papel = getGraphics(); //sirbe para dibujar en el frame figuras basicas 
        
        // "borrando"
        papel.setColor(this.getBackground());
        papel.fillRect(5, 70, 200, 390);
        
        papel.setColor(Color.blue);
        papel.drawRect(15, 70+y, 100, 50);
        papel.drawRect(15, 120+y, 150, 40);
        papel.setColor(Color.green);
        papel.fillRect(20,75+y,90,40);
        papel.setColor(Color.yellow);
        papel.fillRect(20,125+y,140,30);
        papel.setColor(Color.white);
        papel.drawString("Tec Laguna", 30, 100+y);
        papel.setColor(Color.red);
        papel.drawLine(15, 130+y, 165, 130+y);
        papel.drawLine(15, 140+y, 165, 140+y);
        papel.drawLine(15, 150+y, 165, 150+y);
        papel.setColor(Color.black);
        papel.fillOval(35, 160+y, 20, 20+y);        
        papel.fillOval(125, 160+y, 20, 20+y);
        
        try {
            Thread.sleep(100);
        } catch (InterruptedException ex) {
            Logger.getLogger(JFrameDibujo2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButDibujar = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jButMover = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jRadioFrame = new javax.swing.JRadioButton();
        jRadioPanel = new javax.swing.JRadioButton();
        jRadioBoton = new javax.swing.JRadioButton();
        jRadioOtro = new javax.swing.JRadioButton();
        jButVertical = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButDibujar.setText("Dibujar");
        jButDibujar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButDibujarActionPerformed(evt);
            }
        });

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jButMover.setText("Mover");
        jButMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButMoverActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(255, 255, 153));
        jButton1.setText("jButton1");

        buttonGroup1.add(jRadioFrame);
        jRadioFrame.setText("Frame");

        buttonGroup1.add(jRadioPanel);
        jRadioPanel.setText("Panel");

        buttonGroup1.add(jRadioBoton);
        jRadioBoton.setText("Boton");

        buttonGroup1.add(jRadioOtro);
        jRadioOtro.setText("Otro");

        jButVertical.setText("Vertical");
        jButVertical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButVerticalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButDibujar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButMover)
                        .addGap(39, 39, 39)
                        .addComponent(jRadioFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioOtro, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButVertical)
                        .addGap(21, 21, 21)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButDibujar)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButMover)
                    .addComponent(jRadioFrame)
                    .addComponent(jRadioPanel)
                    .addComponent(jRadioBoton)
                    .addComponent(jRadioOtro)
                    .addComponent(jButVertical))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButDibujarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButDibujarActionPerformed
        // TODO add your handling code here:
         dibujar(150,jButton1);
    }//GEN-LAST:event_jButDibujarActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        int x = (int)jSpinner1.getValue();
         dibujar(x, this);
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jButMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButMoverActionPerformed
        // TODO add your handling code here:}
        Component comp = this;
        
        if(jRadioFrame.isSelected()){
            comp = this;
        }
        if(jRadioOtro.isSelected())
        {
            JFrameDibujo2 f = new JFrameDibujo2();
            f.setVisible(true);
            comp = f;
        }
        if(jRadioPanel.isSelected()){
            comp = jPanel1;
        }
        if(jRadioBoton.isSelected()){
            comp = jButton1;
        }
        for(int i=1;i<=200;i+=3)
            dibujar(i,comp);
    }//GEN-LAST:event_jButMoverActionPerformed

    private void jButVerticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButVerticalActionPerformed
        // TODO add your handling code here:
         for(int i=1;i<=200;i+=3)
            dibujarVertical(i,this);
    }//GEN-LAST:event_jButVerticalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameDibujo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameDibujo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameDibujo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameDibujo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameDibujo2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButDibujar;
    private javax.swing.JButton jButMover;
    private javax.swing.JButton jButVertical;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioBoton;
    private javax.swing.JRadioButton jRadioFrame;
    private javax.swing.JRadioButton jRadioOtro;
    private javax.swing.JRadioButton jRadioPanel;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
